export const styles = {
    mainContainer: {
        padding: '20px',
        maxWidth: '1400px',
        margin: '0 auto',
        backgroundColor: '#f5f5f5',
    },
    loading: {
        textAlign: 'center' as const,
        padding: '40px',
        fontSize: '18px',
    },
    error: {
        backgroundColor: '#ffebee',
        color: '#c62828',
        padding: '15px',
        borderRadius: '4px',
        marginBottom: '20px',
    },
    patientInfoSection: {
        backgroundColor: '#fff',
        padding: '30px',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
        marginBottom: '20px',
    },
    gridContainer: {
        display: 'grid',
        gridTemplateColumns: '2fr 1fr',
        gap: '20px',
        marginBottom: '20px',
    },
    leftColumn: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '20px',
    },
    rightColumn: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '20px',
    },
    section: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    },
    timelineSection: {
        backgroundColor: '#fff',
        padding: '30px',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
      headerRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '20px',
      borderBottom: '2px solid #e0e0e0',
      paddingBottom: '15px',
    },
    patientName: {
      margin: 0,
      color: '#333',
      fontSize: '28px',
    },
    actionButtons: {
      display: 'flex',
      gap: '10px',
    },
    editButton: {
      padding: '8px 16px',
      backgroundColor: '#2196F3',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '14px',
    },
    backButton: {
      padding: '8px 16px',
      backgroundColor: '#757575',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '14px',
    },
    infoGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(3, 1fr)',
      gap: '15px',
      marginBottom: '20px',
    },
    infoItem: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '5px',
    },
    label: {
      fontSize: '12px',
      color: '#666',
      fontWeight: 'bold',
      textTransform: 'uppercase' as const,
    },
    value: {
      fontSize: '16px',
      color: '#333',
    },
    doshaBadge: {
      backgroundColor: '#e3f2fd',
      padding: '4px 12px',
      borderRadius: '16px',
      display: 'inline-block',
      fontWeight: 'bold',
      textTransform: 'capitalize' as const,
      color: '#1976d2',
    },
    conditionsSection: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '20px',
      marginTop: '20px',
    },
    conditionBlock: {
      backgroundColor: '#f9f9f9',
      padding: '15px',
      borderRadius: '6px',
    },
    subHeading: {
      margin: '0 0 10px 0',
      fontSize: '16px',
      color: '#555',
    },
    tagContainer: {
      display: 'flex',
      flexWrap: 'wrap' as const,
      gap: '8px',
    },
    tag: {
      backgroundColor: '#e8f5e9',
      color: '#2e7d32',
      padding: '5px 12px',
      borderRadius: '12px',
      fontSize: '14px',
    },
    allergyTag: {
      backgroundColor: '#ffebee',
      color: '#c62828',
    },
    noData: {
      color: '#999',
      fontStyle: 'italic' as const,
      margin: 0,
    },
    assessmentInfo: {
  color: '#666',
  fontSize: '14px',
  marginBottom: '15px',
    },
    doshaResults: {
      marginBottom: '20px',
    },
    doshaBar: {
      marginBottom: '12px',
    },
    progressBarContainer: {
      width: '100%',
      height: '20px',
      backgroundColor: '#e0e0e0',
      borderRadius: '10px',
      overflow: 'hidden',
      marginTop: '5px',
    },
    progressBarFill: {
      height: '100%',
      transition: 'width 0.3s ease',
    },
    resultDosha: {
      fontSize: '16px',
      marginBottom: '15px',
      textAlign: 'center' as const,
    },
    noAssessment: {
      color: '#999',
      fontStyle: 'italic' as const,
      marginBottom: '15px',
    },
    quizButton: {
      width: '100%',
      padding: '12px',
      backgroundColor: '#4CAF50',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '16px',
      fontWeight: 'bold',
    },
    progressCircleContainer: {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  marginBottom: '20px',
  padding: '20px 0',
},
progressCircle: {
  position: 'relative' as const,
  display: 'inline-block',
},
percentageText: {
  position: 'absolute' as const,
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  fontSize: '28px',
  fontWeight: 'bold' as const,
  color: '#4CAF50',
},
progressLabel: {
  marginTop: '10px',
  fontSize: '14px',
  color: '#666',
  fontWeight: 'bold' as const,
},
milestonesList: {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '12px',
},
milestoneItem: {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
},
checkmark: {
  width: '24px',
  height: '24px',
  borderRadius: '50%',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  fontSize: '14px',
  fontWeight: 'bold' as const,
  flexShrink: 0,
},
milestoneName: {
  fontSize: '15px',
},


bmiValueContainer: {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: '10px',
},
bmiValue: {
  fontSize: '48px',
  fontWeight: 'bold' as const,
},
bmiUnit: {
  fontSize: '18px',
  color: '#666',
  marginLeft: '5px',
},
categoryBadge: {
  textAlign: 'center' as const,
  padding: '8px 16px',
  borderRadius: '20px',
  color: 'white',
  fontWeight: 'bold' as const,
  fontSize: '16px',
  margin: '0 auto 20px',
  display: 'inline-block',
  width: '80%',
},
gaugeContainer: {
  position: 'relative' as const,
  marginBottom: '10px',
},
gaugeBar: {
  display: 'flex',
  height: '30px',
  borderRadius: '15px',
  overflow: 'hidden',
},
gaugeSegment1: {
  flex: '18.5',
  backgroundColor: '#2196F3',
},
gaugeSegment2: {
  flex: '6.5', // 25 - 18.5
  backgroundColor: '#4CAF50',
},
gaugeSegment3: {
  flex: '5', // 30 - 25
  backgroundColor: '#FF9800',
},
gaugeSegment4: {
  flex: '10', // 40 - 30
  backgroundColor: '#F44336',
},
gaugePointer: {
  position: 'absolute' as const,
  top: '-5px',
  transform: 'translateX(-50%)',
},
pointerTriangle: {
  width: 0,
  height: 0,
  borderLeft: '8px solid transparent',
  borderRight: '8px solid transparent',
  borderBottom: '12px solid',
},
scaleLabels: {
  display: 'flex',
  justifyContent: 'space-between',
  marginBottom: '20px',
  paddingTop: '5px',
},
scaleLabel: {
  fontSize: '12px',
  color: '#666',
},
legendContainer: {
  display: 'grid',
  gridTemplateColumns: '1fr 1fr',
  gap: '8px',
  marginBottom: '20px',
},
legendItem: {
  display: 'flex',
  alignItems: 'center',
  gap: '6px',
},
legendColor: {
  width: '16px',
  height: '16px',
  borderRadius: '3px',
},
legendText: {
  fontSize: '13px',
  color: '#666',
},
measurementsContainer: {
  display: 'flex',
  justifyContent: 'space-around',
  marginBottom: '20px',
  padding: '15px',
  backgroundColor: '#f9f9f9',
  borderRadius: '8px',
},
measurement: {
  display: 'flex',
  flexDirection: 'column' as const,
  alignItems: 'center',
  gap: '5px',
},
measurementLabel: {
  fontSize: '12px',
  color: '#999',
  textTransform: 'uppercase' as const,
},
measurementValue: {
  fontSize: '18px',
  fontWeight: 'bold' as const,
  color: '#333',
},
adviceContainer: {
  backgroundColor: '#e3f2fd',
  padding: '12px',
  borderRadius: '6px',
  borderLeft: '4px solid #2196F3',
},
adviceText: {
  margin: 0,
  fontSize: '14px',
  color: '#555',
  lineHeight: '1.5',
},
};